### ISSUE TITLE
working implementation for Spring Boot 1.4/1.5

### ISSUE THREAD

**Issue by rivasdiaz** [shrinkwrap/shrinkwrap-springboot#2]
The project is missing a working implementation for SpringBoot 1.4/1.5

**Comment by lordofthejars** [comment]
We are totally aware of it but first we want to validate boot 1.3 approach
and if everyone feels comfortable with it then use similar approach. Do you
see something to improve?

**Comment by rivasdiaz** [comment]
I have a working implementation for 1.4 that I would like to contribute. I based my implementation on ideas from your 1.3 plus core shrinkwrap. Although my code is not perfect and lack enough testing, I would prefer to contribute it so you could review my decision and guide me until completion. I think that would help me understand what is missing on 1.3. I personally have no interest in supporting 1.3 (spring boot is in 1.5 now) but I can help if needed.

**Comment by lordofthejars** [comment]
Hi go ahead then. 1.3 support is finished and I think that 1.4 and 1.5 is
exactly same format.

**Comment by lordofthejars** [comment]
Spring boot 1.3 merged to master.
